In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report
%matplotlib inline

In [2]:
df = pd.read_csv("credit_card_dataset_wo_smote.csv")

In [3]:
df.shape

(52525, 8)

In [4]:
from sklearn import preprocessing

In [5]:
label_encoder = preprocessing.LabelEncoder()

In [6]:
df['merchant']= label_encoder.fit_transform(df['merchant'])
df['merchant'].unique()

array([514, 241, 390, 360, 297, 607, 534, 107, 250, 563, 543, 304, 394,
       308,  42, 557, 379, 409, 331, 570,  29, 231, 324, 467, 387, 351,
       130,  82, 352, 454, 311, 627,  21,  17, 268, 239, 225, 229, 442,
        92, 265, 381, 329, 146, 548, 602, 443,  86, 468, 479, 272, 648,
       309, 298, 117, 194, 589, 271, 403, 436, 153, 270, 172, 237, 392,
       280, 217, 119, 610, 466, 502,   8, 480, 208,  99, 625, 678, 650,
       645,  47, 439,  77, 444, 472, 363, 108, 273, 147, 554, 549, 669,
       483, 162, 349, 175, 421, 300, 595, 198,   4, 210, 522, 681, 657,
       245, 494, 332, 585, 255, 149, 414, 498, 485, 370,  32, 510,  55,
       157, 359, 174, 463, 181, 508,  70, 399,  88, 186, 196, 475, 425,
       431, 327, 346, 328, 597, 491, 450, 378, 183,  67,  73, 691, 256,
        81,  48, 677,  83, 316, 588, 303, 173, 487, 291,  43, 103,   3,
       193, 417,  24,  94, 384, 411, 560, 484, 608, 659, 140, 395, 626,
       342, 523, 664,  12, 462, 295, 121, 118, 504, 635,  53, 632, 427,
       365, 136, 594, 524, 106, 623,  93, 285, 499, 488, 476, 647, 605,
       358,  25, 142, 176, 638, 400, 528, 212, 590, 539,  57,  18, 533,
       559, 404, 224, 536, 518, 284,  52, 236, 267, 631, 616, 313, 156,
       426, 571, 206, 336, 247,  20, 415, 661,  13,  63, 133, 389,  87,
       410, 604, 459, 473,  51, 209, 137, 125, 586, 592, 372, 374, 682,
       144, 355, 474, 177, 191,  36, 243, 686, 189, 666, 428, 302, 644,
        64, 407, 447, 178, 464, 195, 252, 101, 572, 416, 244, 214, 649,
       673, 497,  65, 283,  33, 630, 550, 451, 158, 405,  31, 618, 429,
       219,  59, 141,  27, 110, 545, 287, 521,  79, 622, 503, 315, 587,
       367, 120, 290, 584, 434, 227, 656, 583, 347, 448, 337, 598, 383,
       513, 334, 615, 299, 376, 345, 341, 555, 325, 547, 321, 640, 430,
       676, 582, 281, 301, 165, 687, 601, 354, 511, 131, 200, 135, 600,
       246, 190, 145, 446, 418, 541, 531,  72, 577, 207, 350, 123, 654,
       353,  37, 553, 397, 565, 314, 470, 401, 257, 276,  44, 228, 211,
       575, 481,  50, 667, 323, 456, 393,  89, 264, 574, 159,  40,  91,
       188, 512, 187, 490, 155, 458, 614,  41, 460, 580,  76,  78, 169,
        62, 406, 620, 636, 201, 293, 420,  61, 100, 199, 568, 251, 482,
       343, 655, 599, 234, 366, 179, 111, 261, 413, 185, 611, 672, 683,
       424, 160,  15, 646,  35, 433, 288, 441,   1, 546, 134, 660, 344,
       692, 493, 279,  39, 296, 171, 292, 423, 388,  68,  54, 310, 233,
       629, 402, 362, 202,  74, 262, 689, 561, 573, 449, 223, 684, 564,
       380,  97, 576, 653,  34, 226, 612, 113, 529, 170, 663, 445,  69,
       319,  38, 538, 356,  19, 679, 112, 489, 551, 652, 628, 412,  30,
       552,  85, 506, 115,   6, 152, 326, 537, 567, 386, 205, 507, 596,
       126, 132, 515, 240, 254, 105, 161,  66, 213, 391,  60, 361, 307,
       129, 525, 408,  22,   0, 690, 509, 238, 668, 364, 249, 558, 369,
       658, 220, 333, 520, 258, 432,  16, 143, 216, 556, 486, 371,  23,
        49, 544, 540, 396, 282, 662, 581, 164, 320, 624, 348, 606,  56,
         9, 221, 675, 437,  45, 139, 685, 642, 471, 569, 495, 465,  46,
       680, 305, 127,  10, 104, 435, 192, 519, 639, 114, 651, 263, 151,
       398, 275,  84, 385, 633, 168,   7,  28, 591, 260, 674, 603, 562,
       671, 455, 532, 368, 197, 230, 184, 109, 138, 322, 338, 204, 277,
       154,  80, 163, 148, 182, 440, 452,  95, 102, 501, 461, 643, 566,
        71, 122, 422, 492, 665, 527, 373, 167, 269, 116, 688, 124,   5,
        58, 266, 382, 621, 469, 438, 286, 312, 253, 180, 317, 150, 248,
        11, 166, 128, 526, 477,  26, 294, 419,   2,  14,  98, 670, 617,
       340, 457, 339, 500, 619, 496, 222, 637, 593, 516, 453, 579, 203,
       578, 235, 609, 530, 542, 232, 259, 641, 535, 289, 517, 215, 218,
       505, 274,  90, 377, 634, 335, 357, 330, 242, 613, 375, 318, 278,
        75,  96, 478, 306])

In [7]:
df['category']= label_encoder.fit_transform(df['category'])
df['category'].unique()

array([ 8,  4,  0,  2,  9,  3, 11, 12,  1, 10,  5, 13,  7,  6])

In [8]:
df['job']= label_encoder.fit_transform(df['job'])
df['job'].unique()

array([357, 412, 295, 316, 111, 463,  27, 121, 362, 317, 230, 428, 159,
       427, 296, 373, 351, 145, 178, 307, 272, 340, 256, 106, 453,  56,
       332, 139, 326, 297, 193, 203,  34, 117, 309, 358, 259, 189, 399,
       378, 456, 225, 424,  26, 466, 109, 377, 163, 138, 324,  21, 141,
       441, 217,  20, 114, 314, 461, 167, 120,  83, 158, 471, 392, 186,
       411, 345, 465,  58, 204, 108, 194, 405, 151, 170, 133,  77,  82,
       457, 181, 262, 150, 382, 367, 136, 308, 242, 168,  15, 315, 187,
         8, 140, 188,  40, 394,   7, 212, 387, 440, 179,   3, 343, 470,
       286, 421, 451, 171,  49, 341, 155, 218, 432, 274, 213, 280, 446,
       439, 249, 166, 126, 443, 279,  50, 454, 419,  90, 113, 180, 462,
       275, 278,   5, 287, 191, 101, 353, 110, 288, 107,  78, 434,  59,
       319, 337, 142, 291,  17,  68,  10,  11,  65, 354, 402, 258, 143,
       233, 442, 102, 210, 104,  47, 248,  66, 303, 182, 197,  31, 243,
       152, 359, 247, 129, 327, 323, 220, 228,  93, 363,  29, 257, 361,
       436, 459,  89, 331,  52,  30, 135, 409, 474, 285, 115, 282, 468,
        75,  57, 105, 425, 344, 299, 318,  28, 420, 119, 198,  71, 289,
       368, 325, 264, 328, 346, 232, 384, 209, 437, 246,  96, 103, 268,
       131, 391, 397, 240,  86,   9,  42, 156,  87, 124,  36, 390,  32,
       310, 239,  63,  80, 385, 265, 176, 460, 379, 360, 321, 388, 160,
       263, 472, 254, 347, 455, 292, 423, 165,   4, 222, 435,   2, 231,
       398,  53, 401, 372, 270,  24, 348,  44, 161,  98, 201, 118, 338,
       283, 157, 164,  55,  91,   1, 261, 350, 336,  67, 475,  70, 302,
       128,  95, 250, 304, 413,  81,  43, 464,  39, 298, 330, 371, 184,
       234, 284, 333, 237, 448, 199,  74, 215,  61,  25, 305,  88, 148,
       450, 311, 253,  38,  45, 370, 452, 386, 196,  51, 267,  16, 134,
       339, 395, 365, 127,  13, 227, 207, 173, 252,  73, 393, 375,  41,
       273, 431, 294, 449, 149,  85, 469, 426, 414, 137,  76, 300, 293,
       329, 438,  72, 447, 369, 241, 255, 376, 403,  69, 116, 322, 407,
       175, 364, 458,  64, 352, 271, 473,  94,  23, 320, 235, 335, 238,
       410,  54, 366, 211, 355, 467, 389, 224,  92, 236, 374, 406, 430,
       130, 192, 183, 269, 146, 290, 214, 312, 418, 223, 177, 416, 244,
        46, 444, 301,  97, 349, 266, 276, 112, 154, 216, 200, 400,  79,
        19, 445, 174, 195, 219, 190, 206, 356, 125, 415, 229, 334, 313,
       185, 408, 169, 383, 226, 381, 122, 202, 123, 260, 144, 205,  18,
       404, 422,  62, 417,  14, 208, 132, 221, 380, 147,  99,  35,  12,
       153, 306, 162, 396, 245, 281,   0,  37,  84, 429,   6, 433,  60,
       172, 100,  22,  48, 277, 251, 342,  33])

In [9]:
df['gender']= label_encoder.fit_transform(df['gender'])
df['gender'].unique()

array([0, 1])

In [10]:
df['city']= label_encoder.fit_transform(df['city'])
df['city'].unique()

array([494, 569, 440,  81, 204, 210, 332, 222, 446, 140, 138, 696, 675,
       293, 327, 307, 396, 116, 304, 230, 473, 500, 603, 458, 792,  43,
       656, 259, 336, 774, 813, 752, 639,  50, 786,  68,  61, 254,  11,
       496, 237, 130, 747, 544, 407, 282, 160, 523, 735, 236, 658, 606,
       181, 363, 545,  35, 132, 233, 737,  25, 264,  82, 317, 679, 665,
       168, 633, 771, 766, 517, 745, 585, 129, 258, 239,  93, 700,  70,
       546, 334, 419, 331, 466, 228, 483, 202,  85, 338, 314, 379, 666,
        40, 621, 697, 436, 704, 150, 411, 449, 814, 527, 300,  10, 373,
       701, 335,  88, 588, 812, 751, 214, 167, 231, 268, 426, 225, 101,
       207,  44, 253, 810, 799, 410, 369, 105, 795, 574,  72, 184, 690,
       664, 364, 348, 330,   1, 111, 707, 599, 514, 467, 579, 366,  58,
       811, 731, 424,  26, 674, 271, 243, 248, 382, 720, 414, 375, 431,
       374, 471, 607, 427, 613, 128, 155, 221, 800, 460, 515, 367, 472,
        73, 301, 782, 587, 709, 147, 638,  47, 115, 384, 600, 530, 549,
       464, 760,  45, 677,  92, 755, 441, 573, 762, 241, 454, 636, 796,
       794, 614, 291,  80, 513, 785, 470, 131,  95,  31, 352, 192, 106,
       783, 135,   3, 148, 501, 805, 595, 368, 261, 670, 376, 288, 400,
       651, 421,  13, 308, 117, 833, 198,  37, 180, 827, 563, 476,  21,
       443, 333, 212, 589,  71, 170, 744, 260, 662,  75, 158, 432,  34,
       543, 284, 478, 491, 100, 706, 172, 380, 310, 194, 262,  97,  54,
       326,  32, 252,  22, 347, 815, 159, 320, 615, 191, 343, 566,  62,
       492, 726,  27, 223, 450, 611,  87, 740, 274, 227, 402, 442, 235,
        17, 655, 618,  74,  91, 278, 741, 285, 395, 801,   8, 593,   6,
       688,  41, 404, 179, 444, 510, 770,  90, 306,  42, 250, 266, 287,
        53, 481, 292, 763, 548, 650,  15, 575, 632, 506, 594, 602, 807,
       750, 641, 240, 692, 183, 423, 152, 536, 114, 733, 185, 742, 263,
       218, 208, 439, 584, 564, 468, 249, 551, 592, 102,  59, 378, 727,
       110,  39,  23, 616, 660, 416, 749, 768, 647, 303, 123, 541, 256,
        52, 136,  24, 120, 680,  20, 406, 344, 126, 394, 201,  86, 829,
       746, 695, 761, 346, 831, 162, 399, 780, 276, 836, 693, 826, 462,
       479, 535, 244, 199,  67, 107, 273,  49, 435, 209, 108, 437, 353,
       169, 822, 340, 141, 691, 821, 560, 714, 557, 580, 104, 524, 685,
       787, 229, 678, 453, 257, 390,  96, 488, 238, 112, 354, 325, 412,
       511, 509, 323, 200, 503, 247, 837, 434, 324, 164, 825, 459, 591,
       144, 819, 387, 393, 328, 316,   9, 610, 403, 504, 547, 498, 161,
       682, 127, 311, 451, 275, 255, 711, 174, 397, 568, 784, 757, 556,
       490, 583, 654, 151, 246, 495, 713, 272, 703, 552,  94, 767, 337,
       669, 142, 119, 672, 781, 134,   7, 659, 764, 398, 582, 790, 156,
       372, 645,  56, 232, 428, 806, 389, 698, 646, 817, 668, 455,   2,
       838, 165, 699, 489, 734, 296, 531, 712, 586, 267, 365, 469,  51,
       835, 438, 166, 312, 245, 756, 315, 295, 705, 493, 820, 217, 736,
       350,  83, 508, 302, 211, 154, 661, 635,  64, 487,  65, 286, 640,
       518, 341,  12, 113, 122, 684, 339, 537, 667,  30, 832, 190, 738,
       280, 447, 572,  16, 753, 581, 345, 502, 425, 816, 377,  18, 687,
       624, 625, 133, 139, 505, 802,  57, 630, 290, 629, 597, 149, 728,
       360, 562, 808, 657, 732,  60, 779, 177, 765, 474, 623, 673, 213,
       188, 408, 759, 480, 521, 220, 683, 804,  36, 465, 251, 163, 601,
       124, 818, 578, 525, 532, 773, 370, 224, 329, 793, 186, 477, 189,
       529, 605, 157,  63, 627,  46, 528, 206,  19, 145, 723,  78, 516,
       809, 187, 313, 385, 497, 420, 694, 294, 298, 381, 722, 653, 297,
       512, 482, 526, 717, 203, 448, 828, 648, 567, 571, 176, 626, 676,
       215, 413, 137, 715, 519, 652, 644, 554, 534,  66, 125, 422, 719,
        89, 743, 386, 265, 195, 234, 550, 452, 269, 143,   5, 355, 634,
       565,  98, 642,  29, 559, 359, 788, 197, 484, 776, 777, 299, 570,
       631, 409, 349, 277, 681, 834,  99, 686, 671, 321, 769, 533, 710,
       118,   0, 418, 445, 281, 604, 362, 415, 724, 456, 283, 754, 401,
       405, 596,  77, 457, 371, 739, 663, 553, 171, 216, 103, 109, 577,
       242, 637,  48, 342,  55, 598, 193, 540, 507, 617, 279, 561,  33,
       351, 357, 226, 622, 205, 576, 182, 708,  76, 718, 643, 803, 429,
       146, 609, 558, 620,  79, 309, 319,  84,  69, 178, 725, 628, 758,
       388, 270, 539,   4, 486, 520, 485, 463, 789,  14, 649, 219,  28,
       730, 830, 824, 461, 318, 702, 173, 196, 358, 538, 153, 392, 555,
        38, 322, 689, 499, 823, 619, 608, 797, 305, 721, 542, 612, 417,
       778, 433, 729, 391, 289, 430, 356, 775, 361, 383, 748, 121, 475,
       716, 590, 798, 522, 791, 175, 772])

In [11]:
X = df.drop(columns=["is_fraud", "dob"], axis=1)
Y = df["is_fraud"]

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=0)

In [13]:
classifier = GaussianNB()

In [14]:
classifier.fit(X_train, Y_train)

GaussianNB()

In [15]:
classifier.score(X_train, Y_train)

0.9831370522479397

In [16]:
Y_predicted=classifier.predict(X_test)

In [17]:
cm=confusion_matrix(Y_test, Y_predicted)
cm

array([[15441,   171],
       [   74,    72]], dtype=int64)

In [19]:
report = classification_report(Y_test, Y_predicted, digits=3)
print(report)

              precision    recall  f1-score   support

           0      0.995     0.989     0.992     15612
           1      0.296     0.493     0.370       146

    accuracy                          0.984     15758
   macro avg      0.646     0.741     0.681     15758
weighted avg      0.989     0.984     0.986     15758